---

persistent_memory: true
#auto_install: true
is_reboot: 'y'
#ntp_enabled: true
#ntp_manage_config: true
#ntp_servers:
#  - "0{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
#  - "1{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
#  - "2{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
#  - "3{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"

#ntp_version: "ntp-4.2.6p5-29.el7.centos.x86_64"

#ntp_packages:
#    - "autogen-libopts*.rpm"
#    - "ntpdate*.rpm"
#    - "ntp*.rpm"
