name: lightbits_cluster_3x_target_small_1numa_emulated_ssd_1x_client
description: "3 targets cluster with 1 client"
machines:
- name: s00
  machine_type: target-small-1numa-emulated-ssd
  role: target

- name: s01
  machine_type: target-small-1numa-emulated-ssd
  role: target

- name: s02
  machine_type: target-small-1numa-emulated-ssd
  role: target

- name: client0
  machine_type: initiator-small
  role: initiator
